name = "threads-scheduler"
main = "src/worker.js"
compatibility_date = "2026-09-01"

[vars]
APP_NAME = "Threads 自動排程器"
# 部署後請更新成你的 Worker URL，例如：
# PUBLIC_BASE_URL = "https://threads-scheduler.your-subdomain.workers.dev"
PUBLIC_BASE_URL = "https://threads-scheduler.gogototo24.workers.dev"
# Meta Threads App ID
THREADS_APP_ID = "1726220261769989"

[[d1_databases]]
binding = "DB"
database_name = "threads-scheduler-db"
database_id = "b466efec-10b0-4e6e-9ea9-7f174946fdb4"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "threads-scheduler-media"

[triggers]
crons = ["* * * * *"]
